import React,{Component} from 'react'
import { Collapse } from 'antd';



const Panel = Collapse.Panel;

const customPanelStyle = {
  background: '#f7f7f7',
  borderRadius: 4,
  marginBottom: 24,
  border: 0,
  overflow: 'hidden',
};

const data = [{t:"What makes Our service unique?",d:"We place a very high value on transparency. Here you can monitor and follow all deposits and payouts of any user in real-time at any time."},
{t:"How profit gets generated?",d:"Here you don't have to make contracts or pledge your property. There are no lenders and no debtors. Everything is actualy real simple: one participant asks for help — another one helps. All profits are generated by new investments."},
{t:"I want to Start, what to do?",d:"First Step: Choose the amount to double and provide your personal wallet to receive earned profit.\nSencond Step: Deposit any amount (min 0.005 BTC) to the unique generated deposit address.\nThird Step:Do Not close deposit window and wait for 3 confirmations, then start receiving profit with no further effort."},
{t:'Do we charge any fees for our services?',d:'No, we do not charge any fee for our services or use of this webisite.'},
{t:'Is our website secure?',d:'Yes, we are using a strong 5 Gbps DDoS Protection with 99% up-time guarantee. Complex Layer 7 Protection. Global CDN Acceleration. Global Protected DNS. Web Application Firewall + Certified Domain SSL certificate for secure connection to our website.'},
{t:'Can i make more than one deposit?',d:'Yes, there are no limitations. You can generate as many deposit addresses as you wish, by simply providing another payout address.'},
{t:'When will my deposit show up in the homepage?',d:'Do Not Close the deposit page until you finish deposit. Contact our customer support if your transaction has at least 3 confirmations, and it is still missing on our platform.'},
]


export default class Faq extends Component {
  constructor(props) {
    super(props);
  }

  render() {

    const items = [];


    for(let i=0;i<data.length;i++){
      items.push(
        <Panel header={data[i].t} key={i} style={customPanelStyle}>
          <p>{data[i].d}</p>
        </Panel>
      )
    }

    return (
      <div >


        <Collapse bordered={false} >
          {items}
        </Collapse>


      </div>
    );
  }
}
